name: Ubuntu 20
on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java-version: [11]
      fail-fast: true
      
    runs-on: ubuntu-20.04
    
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Install required packages
        run: |
          sudo apt-get update
      
      - name: Build Chain ${{ matrix.java-version }}
        id: build-chain
        uses: kiegroup/github-action-build-chain@v2.6.25
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP}/my-app-a/${BRANCH}/.ci/pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
